name: Run tests and generate coverage report

on:
  push:
    branches:
      - 'test/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run tests and generate coverage report
        working-directory: BreakoutTests
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          reportgenerator -reports:$(find TestResults -name coverage.cobertura.xml) -targetdir:Report -reporttypes:Html
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: BreakoutTests/Report
