name: Run tests and generate coverage report

on:
  push:
    branches:
      - 'test/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdiplus
          brew install glfw

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        
      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: Build DIKUArcade
        run: |
          cd DIKUArcade
          dotnet build
        
      - name: Run tests and generate coverage report
        working-directory: BreakoutTests
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:Report -reporttypes:Html
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: BreakoutTests/Report
